### ISSUE TITLE
s6-overlay-suexec: Exec format error

### ISSUE THREAD

**Issue by ngn13** [pi-hole/docker-pi-hole#1524] opened 2024-01-05 18:50 UTC
Hello, it seems like the `linux/386` image for version 2023.05.0 and above is broken.

This is a: **Run Issue or bug idk**  

## Details
I copied over the example docker-compose file, made few edits and after running it, I realized that the web server is down. So I checked the logs
and this was what I got:
```
/s6-init: 37: exec: s6-overlay-suexec: Exec format error
``` 
After downgrading couple of times, I found out that the issue occurs in version 2023.05.0 and above

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian GNU/Linux 11 (bullseye)** 
  * Hardware: **PC**
  * Kernel Architecture: 32bit
  * Docker Install Info and version: 
     - official image version 2023.05.0 (and above) 
     - docker-compose version 1.25.0 
     - docker version 20.10.5+dfsg1
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```yaml
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.03.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "127.0.0.1:8080:80/tcp"
    environment:
      TZ: 'Europe/Istanbul'
      WEBPASSWORD: 'verysecureandrealpasswordthatidefinitelyforgottoremove'
    volumes:
      - './pihole:/etc/pihole'
      - './dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
```

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by xrogeman** [comment] 2024-06-14 10:14
Hi, i have the same error
were you able to solve it?

**Comment by rdwebdesign** [comment] 2024-06-14 15:59
`Exec format error` means your Docker is using the wrong image architecture.

**Comment by ngn13** [comment] 2024-06-14 16:09
docker pulls the correct version for your arch from the docker hub so that's not possible and the issue is most likely related to pi-hole docker packaging

**Comment by PromoFaux** [comment] 2024-06-14 17:32
Digging into this, it would appear that the following change is the relevant one:

https://github.com/pi-hole/docker-pi-hole/commit/69e55ac143e629d53233982abbbd220af585d562

Interesting that this was not detected earlier, I guess it shows how very few people are running the 32bit OS these days.

The good news is, with Pi-hole v6 (currently available in beta on the `development-v6` branch of this repo) no such issue exists as we have entirely removed the need for s6 overlay.

If I can find out the reason for this in the meantime i'll try to fix it in the v5 image, but I cannot exactly see what has gone wrong here.

How come you are using the 32 bit OS? Are you limited by hardware? 

I just about managed to get docker installed on a 32-bit debian 11 and am able to reproduce

**Comment by yubiuser** [comment] 2024-06-14 17:35
Maybe

```
  DETECTED_ARCH=$(dpkg --print-architecture)
  ```
  
  and
  
  ```
  DETECTED_ARCH=$(arch)
```

have different outputs?

**Comment by PromoFaux** [comment] 2024-06-14 17:38
That said, Testing the before and after, I cannot see why it would fail to download the correct s6 version on image creation.

![image](https://github.com/pi-hole/docker-pi-hole/assets/1998970/04bdd17d-0c64-440a-a04c-76ef14511fd6)

Before that commit, we used `dpkg --print-architecture` to detect the arch. If it returned `i386` then we would transform that to `i686` and download the relevant release here: https://github.com/just-containers/s6-overlay/releases/download/v3.1.1.2/s6-overlay-i686.tar.xz

however after that commit we switched to using `arch` to detect the arch - which returns `i686`, so no tranformation needed, and the correct s6 version should be downloaded the same as before... unsure what's happened here!

**Comment by yubiuser** [comment] 2024-06-14 17:44
Maybe i486 would be needed?

https://github.com/just-containers/s6-overlay?tab=readme-ov-file#which-architecture-to-use-depending-on-your-targetarch

**Comment by ngn13** [comment] 2024-06-14 17:49
> The good news is, with Pi-hole v6 (currently available in beta on the development-v6 branch of this repo) no such issue exists as we have entirely removed the need for s6 overlay.
oh, I'm happy to hear that!

> How come you are using the 32 bit OS? Are you limited by hardware?
I'm using a 64 bit system but I have an old 32 bit laptop (I think it's from 2008) which I use for self-hosting random stuff on my LAN

> I just about managed to get docker installed on a 32-bit debian 11 and am able to reproduce
hope you guys will be able to figure it out

**Comment by rdwebdesign** [comment] 2024-06-14 17:52
We need to be sure what image docker is pulling.

What is the output of `docker image inspect pihole/pihole:2023.05.2 -f "{{.Architecture}} {{ .Variant}}  {{.Os}}"` _(Please, use the correct tag for your image)_.

**Comment by PromoFaux** [comment] 2024-06-14 18:15
It's definitely pulling the correct image for the arch

![image](https://github.com/pi-hole/docker-pi-hole/assets/1998970/e36bfe69-d19b-4863-8151-5e2bbad554df)

It's an issue with either s6 overlay, or the detection of the arch that's causing the issues. I'm able to repro the issue

![image](https://github.com/pi-hole/docker-pi-hole/assets/1998970/a7608cca-4a96-405c-95bc-f4369b6161ab)

**Comment by PromoFaux** [comment] 2024-06-14 18:17
> Maybe i486 would be needed?

I'm not sure. Before that change we always pulled `i686`, so in theory nothing should have changed here, as the output of `arch` is `i686`. Maybe worth trying a newer version of s6 overlay. (Or just releasing v6 😉 )

**Comment by PromoFaux** [comment] 2024-06-14 18:26
Oddly... if I build `master` on this 32 bit debian 11 vm it works fine

![image](https://github.com/pi-hole/docker-pi-hole/assets/1998970/1e3aa07a-841a-4841-b5e0-0c00614c38bd)

![image](https://github.com/pi-hole/docker-pi-hole/assets/1998970/d5eac509-2b0b-4309-b440-c4eabcc7976b)

**Comment by yubiuser** [comment] 2024-06-14 18:37
Maybe it was a hiccup in the build process causing the issue?

**Comment by xrogeman** [comment] 2024-06-14 19:27
> Digging into this, it would appear that the following change is the relevant one:
> 
> [69e55ac](https://github.com/pi-hole/docker-pi-hole/commit/69e55ac143e629d53233982abbbd220af585d562)
> 
> Interesting that this was not detected earlier, I guess it shows how very few people are running the 32bit OS these days.
> 
> The good news is, with Pi-hole v6 (currently available in beta on the `development-v6` branch of this repo) no such issue exists as we have entirely removed the need for s6 overlay.
> 
> If I can find out the reason for this in the meantime i'll try to fix it in the v5 image, but I cannot exactly see what has gone wrong here.
> 
> How come you are using the 32 bit OS? Are you limited by hardware?
> 
> I just about managed to get docker installed on a 32-bit debian 11 and am able to reproduce


running ubuntu on an old laptop 32 bits

OS Information 	linux i686 Ubuntu 18.04.6 LTS
Kernel Version 	4.15.0-213-generic
Total CPU 	2
Total memory 	2.1 GB

![image](https://github.com/pi-hole/docker-pi-hole/assets/129813482/aaec9a7b-e6aa-4053-aeb7-7d7641e91532)

**Comment by PromoFaux** [comment] 2024-06-15 15:26
OK, so on the CI - it looks like the `linux/386` image is being detected as `x86_64`. No bueno!

```
2024-05-08T20:07:46.6838084Z #30 [linux/386 5/7] RUN bash -ex install.sh 2>&1 &&     rm -rf /var/cache/apt/archives /var/lib/apt/lists/*
2024-05-08T20:07:46.6839356Z #30 0.071 + mkdir -p /etc/***/
2024-05-08T20:07:46.6840102Z #30 0.073 + mkdir -p /var/run/***
2024-05-08T20:07:46.6840722Z #30 0.075 + CORE_LOCAL_REPO=/etc/.***
2024-05-08T20:07:46.6841377Z #30 0.075 + WEB_LOCAL_REPO=/var/www/html/admin
2024-05-08T20:07:46.6842150Z #30 0.075 + setupVars=/etc/***/setupVars.conf
2024-05-08T20:07:46.6842862Z #30 0.076 ++ cat /***.docker.tag
2024-05-08T20:07:46.6843411Z #30 0.078 + DOCKER_TAG=2024.05.0
2024-05-08T20:07:46.6844007Z #30 0.079 + [[ 2024.05.0 = \n\i\g\h\t\l\y ]]
2024-05-08T20:07:46.6844629Z #30 0.079 + [[ 2024.05.0 = \d\e\v ]]
2024-05-08T20:07:46.6845184Z #30 0.079 + detect_arch
2024-05-08T20:07:46.6845654Z #30 0.080 ++ arch
2024-05-08T20:07:46.6846101Z #30 0.082 + DETECTED_ARCH=x86_64
2024-05-08T20:07:46.6846655Z #30 0.082 + S6_ARCH=x86_64
```

**Comment by PromoFaux** [comment] 2024-06-15 15:38
Simple test given the following Dockerfile:

```Dockerfile
FROM debian

RUN echo $(arch)
RUN echo $(dpkg --print-architecture)
```

And then building with `docker buildx build --platform=linux/i386 . --progress=plain --no-cache`

The output from the two `RUN` lines as follows:

```
#6 [2/3] RUN echo $(arch)
#6 0.202 x86_64
#6 DONE 0.2s

#7 [3/3] RUN echo $(dpkg --print-architecture)
#7 0.365 i386
#7 DONE 0.4s
```

So it appears that `arch` is not providing the correct response with `docker buildx`, but `dpkg --print-architecture` is. Curious.

I can think of a dirty workaround to make this work, but will try to get to the bottom of it first...

**Comment by PromoFaux** [comment] 2024-06-15 18:07
@ngn13 , @xrogeman - The above PR has been merged into dev. Please try the `:dev` tag (still based on latest v5 components of Pi-hole) on your 32 bit machines, it should work now. Once you have confirmed I will merge into master and tag a new release

![image](https://github.com/pi-hole/docker-pi-hole/assets/1998970/074e2be2-771c-4070-be77-9e092f3205dc)

**Comment by PromoFaux** [comment] 2024-06-16 09:30
Is now fixed in https://github.com/pi-hole/docker-pi-hole/releases/tag/2024.06.0 - apologies it took so long to get around to, somehow missed the initial report!

**Closed by PromoFaux** 2024-06-16 09:30 UTC

**Comment by Shnitz** [comment] 2024-11-01 18:34
This is happening to me again in 2024.07.0, reverting to 2024.06.0 fixes it.
