### ISSUE TITLE
setting QUERY_LOGGING from docker env variable doesn't work

### ISSUE THREAD

**Issue by PhracturedBlue** [pi-hole/docker-pi-hole#753] opened 2021-01-09 17:52 UTC
### Versions
 -  Pi-hole version is v5.2.2 (Latest: v5.2.2)
 -  AdminLTE version is v5.2.2 (Latest: v5.2.2)
 -  FTL version is v5.3.4 (Latest: v5.3.4)

### Platform
- Alpine 3.12 
- Platform:  Raspberry Pi

### Expected behavior

running `docker run -e QUERY_LOGGING=false pihole/pihole` should result in log querying being disabled.

### Actual behavior / bug

Query logging remains enabled:
```
grep QUERY_LOGGING setupVars.conf
QUERY_LOGGING=true
```

### Steps to reproduce

docker run --rm -d --name pihole -e QUERRY_LOGGING=false pihole/pihole
docker exec pihole grep QUERY_LOGGING /etc/pihole/setupVars.conf

### Additional context

The issue appears to be that ~~/etc/.pihole/automated\ install/basic-install.sh~~ /root/ph_install.sh hardcodes QUERY_LOGGING=true which overrides the environment variable

**Comment by dschaper** [comment] 2021-01-09 18:25
> QUERRY_LOGGING=false
> QUERY_LOGGING=true

Is this a typo?

**Comment by PhracturedBlue** [comment] 2021-01-09 18:57
Just in my bug report (fixed).  The actual docker call did not have that typo and does demonstrate this bug

**Comment by PromoFaux** [comment] 2021-01-09 19:48
As far as I can tell, it's to do with where we source `. /opt/pihole/webpage.sh` (in both `start.sh` and `bash_functions.sh`), which in turn sources `basic-install.sh` - and defaults the value to `true`

Playing about with some tweaks to things on the docker side now

**Comment by PromoFaux** [comment] 2021-01-09 21:26
Also, closing as a duplicate of #744

**Closed by PromoFaux** 2021-01-09 21:26 UTC
