### ISSUE TITLE
Pihole Docker container not starting

### ISSUE THREAD

**Issue by darkps10n** [pi-hole/docker-pi-hole#851] opened 2021-05-02 19:44 UTC
This is a: **Run Issue**  

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

cant find any

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian** 
  * Hardware: PC 
  * Kernel Architecture: x86/amd64 
  * Docker Install Info and version: 
    - Software source: official docker-ce 20.10.6 
    - Supplimentary Software: Openmediavault
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here

```  pihole:
    container_name: pihole
    restart: always
    image: pihole/pihole
    ports:
      - "192.168.10.1:53:53/tcp"
      - "192.168.10.1:53:53/udp"
      - "192.168.10.1:82:80/tcp"
    volumes:
      - '/srv/dev-disk-by-label-Data/docker/containers/pihole:/etc/pihole/'
      - '/srv/dev-disk-by-label-Data/docker/containers/pihole/dnsmasq.d:/etc/dnsmasq.d'
    environment:
      - ServerIP="192.168.10.1"
      - WEBPASSWORD=***********
      - DNS1=8.8.8.8
      - DNS2=8.8.4.4
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.mydomain
      - VIRTUAL_PORT=82
    extra_hosts:
      - "pihole.mydomain:192.168.10.1"
```
3. any additional info to help reproduce

```
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
sudo: unable to open /etc/sudoers: Permission denied
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
::: Testing pihole-FTL DNS: [cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

## These common fixes didn't work for my issue

- [x ] I have tried removing/destroying my container, and re-creating a new container
- [x ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [x ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [x ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [x ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by awaldeck** [comment] 2021-06-10 09:08
Seems like the problem is pihole docker image doesnt have the permissions for "sudo: unable to open /etc/sudoers: Permission denied"

Any one know what the permissions should be?

**Comment by awaldeck** [comment] 2021-06-11 19:58
No body knows

**Comment by dschaper** [comment] 2021-06-14 19:26
Is that your entire `docker-compose.yml`?

Note: `- VIRTUAL_PORT=82` isn't a valid environment variable. 


> Seems like the problem is pihole docker image doesnt have the permissions for "sudo: unable to open /etc/sudoers: Permission denied"

No, it's failing at the `pihole-FTL test` command, the sudoers issue isn't an issue.

https://github.com/pi-hole/docker-pi-hole/blob/2e04f5abee04e7517fbc8ec1186375c7b7a77839/bash_functions.sh#L260-L261

**Comment by awaldeck** [comment] 2021-06-14 19:48
> sudo -u ${DNSMASQ_USER:-root} pihole-FTL test || exit 1

Yes that is the whole file except for the 
version: '3'
services:
above that

**Comment by dschaper** [comment] 2021-06-15 20:48
How are you using OMV? Are you using the image or is it also in a docker container?

**Comment by awaldeck** [comment] 2021-06-15 21:19
Straight install on hardware from the image

**Comment by dschaper** [comment] 2021-06-15 22:38
So you are not running Debian, you are running the OMV image?

**Comment by awaldeck** [comment] 2021-06-15 22:46
root@openmediavault:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by dschaper** [comment] 2021-06-15 22:59
You'll need to ask OMV what they have set up differently for docker. There's a number of hits for a search of "OMV docker pi-hole" and it looks like there is some changes or modifications needed for things to work with the OMV OS.

It is based on Debian but it is not Debian. It is modified and has changes from plain vanilla Debian.

**Comment by awaldeck** [comment] 2021-06-16 09:30
This is also what I suspect as it happened after running apt update, but did container updates at the same time. They sent me here but I'll see what I can achieve on that side. Thank you any way

**Comment by darkps10n** [comment] 2021-06-16 17:23
I tried doing that, even went as far back as version 4.4. Same result.

**Comment by dschaper** [comment] 2021-06-16 18:09
Okay, then the problem highly likely to be in the OS.

I'm going to close this issue but feel free to reopen if you have new information to investigate.

**Closed by dschaper** 2021-06-16 18:09 UTC
