### ISSUE TITLE
pi.hole is wrong IP

### ISSUE THREAD

**Issue by nimbius** [pi-hole/docker-pi-hole#871] opened 2021-06-28 00:07 UTC
pihole picks its IP for the pi.hole host from /etc/hosts.  this is incorrect, as hosts isnt guaranteed to have the public facing service IP of the container.  IP should be taken and set from setupvars if possible.

**Comment by dschaper** [comment] 2021-08-20 00:09
I think this may actually be the new FTL behavior where it determines the IP address on it's own. `ServerIP` used to override this but that no longer works.

**Comment by dschaper** [comment] 2021-08-20 00:10
@PromoFaux This was going to be fixed so that `ServerIP` writes the `REPLY_ADDR4` variable, wasn't it?

**Comment by dschaper** [comment] 2021-08-20 00:11
https://github.com/pi-hole/docker-pi-hole/blob/master/start.sh#L79 should write to `REPLY_ADDR4` in `pihole-FTL.conf`.

**Comment by dschaper** [comment] 2021-08-20 00:19
Yep, confirmed. `docker exec` in to the container and set that line in the config file then TERM `pihole-FTL` and it will restart and respond with the intended IP address for `pi.hole`.

**Comment by PromoFaux** [comment] 2021-08-20 10:53
> @PromoFaux This was going to be fixed so that `ServerIP` writes the `REPLY_ADDR4` variable, wasn't it?

Ah yes... sorry, been a bit distracted of late! But I see you have a PR... so I will approve that

**Comment by dschaper** [comment] 2021-08-20 12:35
No worries!

**Comment by 73VW** [comment] 2021-09-23 20:14
## pi.hole is again resolving to wrong IP since I updated today to latest version.

```bash
nslookup pi.hole
Server:         172.21.192.1
Address:        172.21.192.1#53

Non-authoritative answer:
Name:   pi.hole
Address: 172.21.0.2
Name:   pi.hole
Address: ::
```

### docker-compose.yml (based on docker-compose example and [this](https://github.com/pi-hole/docker-pi-hole/blob/master/docker_run.sh))
```yml
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi.hole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Zurich'
      ServerIP: 192.168.0.200/24
      VIRTUAL_HOST: pi.hole 
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

### docker inspect pihole
```json
[
    {
 ...
        "Image": "sha256:745d0f221dbfbb0945ee1e5ff44774275e85c58e9a5fb3c8431946974815dcda",
        "ResolvConfPath": "/var/lib/docker/containers/edd9a4b53b83954b5f5242c57f9034e4bd51163f9f3d96fe2bf20bb980c2feb4/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/edd9a4b53b83954b5f5242c57f9034e4bd51163f9f3d96fe2bf20bb980c2feb4/hostname",
        "HostsPath": "/var/lib/docker/containers/edd9a4b53b83954b5f5242c57f9034e4bd51163f9f3d96fe2bf20bb980c2feb4/hosts",
        "LogPath": "/var/lib/docker/containers/edd9a4b53b83954b5f5242c57f9034e4bd51163f9f3d96fe2bf20bb980c2feb4/edd9a4b53b83954b5f5242c57f9034e4bd51163f9f3d96fe2bf20bb980c2feb4-json.log",
        "Name": "/pihole",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/73vw/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d:rw",
                "/home/73vw/docker/pihole/etc-pihole:/etc/pihole:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "pihole_default",
            "PortBindings": {
                "53/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "53"
                    }
                ],
                "53/udp": [
                    {
                        "HostIp": "",
                        "HostPort": "53"
                    }
                ],
                "67/udp": [
                    {
                        "HostIp": "",
                        "HostPort": "67"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": [
                "NET_ADMIN"
            ],
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/5929faa551fb90e3d685ac29c8ce6b648a84428935f19cb8daab55c71c0ace21-init/diff:/var/lib/docker/overlay2/0d0368fe5729487f04c0683198c3f546e134aa31e9155a719bbd9003ce21705d/diff:/var/lib/docker/overlay2/79e2d9a714f0ca4706b9d35a6c1f94036e65d27b644f26cdd7973a366bf12da3/diff:/var/lib/docker/overlay2/99d37d762e38d8c38a0991701db2639ac40ad6787c5ef8f56513ea4dae83a0f1/diff:/var/lib/docker/overlay2/b6fd496bf56aa10cabf434a9e3c85790ba3db952831d4414cbe56bc7d540e60e/diff:/var/lib/docker/overlay2/f11cdc680170ebd6b76dd7afe017428c44b94482d33242664d5987f6526bb366/diff:/var/lib/docker/overlay2/4be3992ee686b76554494ee29e17661eb9c0558f578eee5d82eb4d3897ac67d2/diff:/var/lib/docker/overlay2/33753fbc999e03542b279c53967e1d68a917f240c8f113258d6fba791ab118d7/diff:/var/lib/docker/overlay2/b29d5d06cbe864244da4461c9360f53de4d4fc30b594a0555c67c6ebef455f03/diff",
                "MergedDir": "/var/lib/docker/overlay2/5929faa551fb90e3d685ac29c8ce6b648a84428935f19cb8daab55c71c0ace21/merged",
                "UpperDir": "/var/lib/docker/overlay2/5929faa551fb90e3d685ac29c8ce6b648a84428935f19cb8daab55c71c0ace21/diff",
                "WorkDir": "/var/lib/docker/overlay2/5929faa551fb90e3d685ac29c8ce6b648a84428935f19cb8daab55c71c0ace21/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/73vw/docker/pihole/etc-pihole",
                "Destination": "/etc/pihole",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/73vw/docker/pihole/etc-dnsmasq.d",
                "Destination": "/etc/dnsmasq.d",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "pi.hole",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "53/tcp": {},
                "53/udp": {},
                "67/udp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "TZ=Europe/Zurich",
                "ServerIP=192.168.0.200/24",
                "VIRTUAL_HOST=pi.hole",
                "PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "ARCH=arm64",
                "UBUNTU_SUITE=buster",
                "DOCKER_REPO=docker.io/pihole/debian-debootstrap",
                "PIHOLE_ARCH=arm64",
                "PIHOLE_TAG=pihole/pihole:2021.09-arm64-buster",
                "S6OVERLAY_RELEASE=https://github.com/just-containers/s6-overlay/releases/download/v2.1.0.2/s6-overlay-aarch64.tar.gz",
                "PIHOLE_INSTALL=/etc/.pihole/automated install/basic-install.sh",
                "PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf",
                "PHP_ERROR_LOG=/var/log/lighttpd/error.log",
                "IPv6=True",
                "S6_LOGGING=0",
                "S6_KEEP_ENV=1",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=2",
                "FTL_CMD=no-daemon",
                "DNSMASQ_USER=root",
                "VERSION=v5.9"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "dig +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1"
                ]
            },
            "Image": "pihole/pihole:latest",
            "Volumes": {
                "/etc/dnsmasq.d": {},
                "/etc/pihole": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/s6-init"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "09bcf3b132d64fc22df8a66f3098c815673f9704680d68d306f2ce5029755ded",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "pihole",
                "com.docker.compose.service": "pihole",
                "com.docker.compose.version": "1.21.0",
                "image": "pihole/pihole:v5.9_arm64",
                "maintainer": "adam@diginc.us",
                "url": "https://www.github.com/pi-hole/docker-pi-hole"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "75a22a8e55d883bf4a18201cdbd631b56e075314e25c2944503fd9faac62f65a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "53/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "53"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "53"
                    }
                ],
                "53/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "53"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "53"
                    }
                ],
                "67/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "67"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "67"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "80"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/75a22a8e55d8",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "pihole_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "edd9a4b53b83",
                        "pihole",
                        "pi.hole"
                    ],
                    "NetworkID": "a9979218f9cb764811a4f28f6506f9d0da1a8d2061eaed7ccff315b784b47383",
                    "EndpointID": "ebd82bf3b4215fa50b2366b3e57c838431c48cf80d94c4b5fe16e9dcc9fb3857",
                    "Gateway": "172.21.0.1",
                    "IPAddress": "172.21.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:15:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

```bash
$ docker exec -it pihole bash
root@pi:/# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.21.0.2      pi.hole pi
```

Have I missed something?

**Comment by dschaper** [comment] 2021-09-23 20:18
Try using the IP only for `ServerIP`, you have it with CIDR notation.

**Comment by 73VW** [comment] 2021-09-23 20:25
@dschaper thank you very much, that was the problem!

**Comment by dschaper** [comment] 2021-09-23 20:39
Closing since it looks like we have fixed it.

**Closed by dschaper** 2021-09-23 20:39 UTC
Labels: bug
