### ISSUE TITLE
Running PiHole on alternative web port does not work

### ISSUE THREAD

**Issue by MatejKovacic** [pi-hole/docker-pi-hole#1134] opened 2022-07-09 07:22 UTC
This is a: **Bug**  

## Details
I have a Debian 11 server, running Nginx, Wireguard and OpenVPN. I have installed Pihole docker, however, I want that Pihole web interface is accessible on wg0 and tun0 interfaces only and on port 8080.

Here is my `docker-compose.yml` file:

```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Ljubljana' #this is the time zone
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
Web service is obviously running:

```
sudo netstat -pluton | grep docker
tcp        0      0 0.0.0.0:4430            0.0.0.0:*               LISTEN      1291/docker-proxy    off (0.00/0/0)
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1279/docker-proxy    off (0.00/0/0)
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      1317/docker-proxy    off (0.00/0/0)
udp        0      0 0.0.0.0:53              0.0.0.0:*                           1331/docker-proxy    off (0.00/0/0)
udp        0      0 0.0.0.0:67              0.0.0.0:*                           1303/docker-proxy    off (0.00/0/0)
```

But when I try to connect to this port, I get an error:
```
curl localhost:8080
curl: (56) Recv failure: Connection reset by peer
```

## Related Issues
- [X] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: **Debian 11.3**
  * Hardware: PC (x86_64)
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: official docker-ce (docker-compose version 1.25.0; Docker version 20.10.5+dfsg1, build 55c4c88)
    - Supplimentary Software: /
  * Hardware architecture: 64-bit
  * 

## These common fixes didn't work for my issue

- [X] I have tried removing/destroying my container, and re-creating a new container
- [X] I have tried fresh volume data by backing up and moving/removing the old volume data
- [X] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [X] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ X I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by MatejKovacic** [comment] 2022-07-09 07:54
BTW, **inside** docker (`sudo docker exec -it pihole bash`), web interface is working (`curl localhost` returns HTML).

**Comment by PromoFaux** [comment] 2022-07-09 16:36
Hmm, I can't see any reason why this wouldn't be working, other than:

> I want that Pihole web interface is accessible on wg0 and tun0 interfaces only

> ```
> curl localhost:8080
> curl: (56) Recv failure: Connection reset by peer
> ```

Are you certain that the `curl` request is going via the `wg0` or `tun0` interface? 

Are you able to browse the web interface from another device?

**Comment by MatejKovacic** [comment] 2022-07-09 17:11
Actually, I ran this curl command **on a server** (where OpenVPN and Wireguard are running). But if I connect to a VPN server with OpenVPN client or WG peer and enter the internal (VPN) IP of a server (i. e. `curl 10.10.8.1:8080`), I get `curl: (7) Failed to connect to 10.10.8.1 port 8080: Connection refused`.

Please note that on this server I already had a web interface.

Also, I tried to set up a test server with WG and OVPN and there PiHole is working just fine.

**Comment by PromoFaux** [comment] 2022-07-09 17:30
Using your compose file, I am unable to reproduce the issue. That said, I don't have any other fancy networking set up...

![image](https://user-images.githubusercontent.com/1998970/178116556-0b774774-5e2c-42c0-bdd5-8fe79851ceba.png)

**Comment by MatejKovacic** [comment] 2022-07-09 18:44
OK... I guess, I will set up network part from the scratch, could be some problem with iptables of ufw...

**Comment by ryancastro** [comment] 2022-07-10 00:01
I'm actually experiencing something very similar. here's my docker-compose:
`version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: proxy-dns
    restart: unless-stopped
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://9.9.9.9/dns-query,https://149.112.112.9/dns-query"

      # Listen on an unprivileged port
      - "TUNNEL_DNS_PORT=5053"

      # Listen on all interfaces
      - "TUNNEL_DNS_ADDRESS=0.0.0.0"
    ports:
      - "5053:5053/udp"
    networks:
       piholenet:
         ipv4_address: '172.19.0.3'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    network_mode: host

    environment:
      TZ: 'America/Boise'
      WEB_PORT: 8081

    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
networks:
  piholenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
`

In this configuration, I'm forwarding through CloudFlared, I'm also running in host network mode because I'm doing DHCP and that was easiest.

I did create a static IP address through piholenet for CloudFlared, but pihole isn't using it, so I don't think it's related. WEB_PORT appears to be completely ignored, no matter what I set that value to, Pihole listens on port 80.

**Comment by PromoFaux** [comment] 2022-07-10 10:35
@ryancastro likely a different issue in your case. 

Inside your running pihole container, what is the value of the `server.port` setting in `/etc/lighttpd/lighttpd.conf` ?

**Comment by ryancastro** [comment] 2022-07-10 15:51
>  server.port                 = 80
A nice, static port 80.

If it's unrelated, I'll hope not to muddy this original issue up. Maybe I jumped the gun and assumed it was just the same, since it was on  :latest  with presumably same symptoms. Thoughts? I appreciate the quick help!

**Comment by PromoFaux** [comment] 2022-07-10 16:18
Closing for now, feel free to re-open if it is still thought that this is a bug

**Closed by PromoFaux** 2022-07-10 16:18 UTC
