### ISSUE TITLE
Upstream DNS server setting is not persistent

### ISSUE THREAD

**Issue by LightningRhino** [pi-hole/docker-pi-hole#470] opened 2019-06-01 11:42 UTC
This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I enter a custom upstream DNS server in the "Custom1" field and furthermore delete the standard servers (Google (ECS).
## Expected Behavior

The custom upstream DNS server setting should be persistent through updating the docker image.
## Actual Behavior

With each new version I always have to make my custom dns setting again and uncheck the google dns server entries.
## Possible Fix

Perhaps an entry in any persistent .conf.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. docker run -d \
    --name mypihole \
    --net=host \
    -v phlcnf-vol:/etc/pihole/ \
    -v phldnsmsq-vol:/etc/dnsmasq.d/ \
    -e ServerIP="192.168.178.2" \
    -e TZ=Europe/Berlin \
    --restart=always \
    --dns=127.0.0.1 --dns=192.168.178.1 \
    pihole/pihole:latest
2. 
3. 
4. 

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 
https://github.com/pi-hole/docker-pi-hole/issues/259
https://github.com/pi-hole/docker-pi-hole/issues/118

## Your Environment 

* Docker Host Operating System and OS Version: Raspbian GNU/Linux 9
* Docker Version: Docker version 18.09.0, build 4d60db4
* Hardware architecture:  Linux dockerpi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

**Comment by Freekers** [comment] 2019-06-01 19:23
Possible duplicate of: https://github.com/pi-hole/docker-pi-hole/issues/467
This issue was not present before version 4.3.1-1

**Comment by diginc** [comment] 2019-06-01 19:48
For now use version 4.3.1, I'm working on a fix for 4.3.1-2

**Comment by diginc** [comment] 2019-06-01 20:31
closing duplicate

**Closed by diginc** 2019-06-01 20:31 UTC

**Comment by LightningRhino** [comment] 2019-07-03 10:51
Problem still exists. Even with the latest 4.3.1. Please fix.

**Comment by shadowofsilicon** [comment] 2019-07-03 20:43
I have this issue too.
It is not a duplicate of #467.

The issue described above is that the install script overwrites any DNS server entries already present in setupVars.conf with the DNS servers set by environment variables in the `docker run` command, or, if not set, the hard-coded defaults.

Sure, one can work around this issue by setting environment variables, but that is not the point.  The expected behavior is that once a user uses the WebAdmin to set their chosen servers, they should not be overwritten by the install/setup script when the container is replaced with a new one.

**Comment by Krautmaster** [comment] 2024-01-26 17:15
still open
