### ISSUE TITLE
container resolv.conf creating incorrect loopback address

### ISSUE THREAD

**Issue by SeanChristopherConway** [pi-hole/docker-pi-hole#410] opened 2019-02-02 17:13 UTC
Here is the issue I am seeing:

::: Starting docker specific setup for docker pihole/pihole
WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)

nameserver 127.0.0.11

**Comment by UniverseXXX** [comment] 2019-02-04 22:16
I've got similar issue. Here is my docker-compose:
``
  Pi-hole:
    container_name:   "Pi-hole"
    image:            "pihole/pihole:latest"
    restart:          always
    networks:
      local_net:
        ipv4_address: 192.168.1.120
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - /Dockers/Pi-hole/etc:/etc/pihole/
      - /Dockers/Pi-hole/dnsmasq.d:/etc/dnsmasq.d/
    environment:
      - ServerIP=192.168.1.120
      #- ServerIPv6=${IPv6}
      - DNSMASQ_LISTENING=all
      - TZ=Europe/London
``

**Comment by diginc** [comment] 2019-02-05 05:15
when `--dns 127.0.0.1 --dns 1.1.1.1` is not updating the resolv.conf that usually means your version of docker is somehow not respecting those arguments.  Others have used more forceful means of overwriting /etc/resolv.conf in this case such as a volume mount to overwrite /etc/resolv.conf:

```
$ echo -e "nameserver 127.0.0.1\nnameserver 1.1.1.1" > overwrite_resolv.conf
$ docker run -it -v $(pwd)/overwrite_resolv.conf:/etc/resolv.conf debian cat /etc/resolv.conf
nameserver 127.0.0.1
nameserver 1.1.1.1
```

**Comment by mr-bolle** [comment] 2019-02-05 06:16
Hi @UniverseXXX, you set the ServerIP to 192.168.1.120 and the ipv4_address to the same. The ServerIP I use the host IP from the Server, and the ipv4 to the container IP.

**Comment by UniverseXXX** [comment] 2019-02-05 06:31
Thanks @diginc This has fixed the issue.

**Comment by gmcinalli** [comment] 2019-02-07 21:24
Thanks @diginc I fixed with your workaround, any updates on a definitive fix on this?

**Comment by nightah** [comment] 2019-03-12 11:07
Docker specifying the nameserver in the container `/etc/resolv.conf` as `127.0.0.11` is correct that's Docker networks DNS resolver. This can be queried for container network hostnames and will then iterate through the DNS specified in the `--dns` options.

Per [Embedded DNS server in user-defined networks](https://docs.docker.com/v17.09/engine/userguide/networking/configure-dns/):

`--dns=[IP_ADDRESS...]`
The IP addresses passed via the --dns option is used by the embedded DNS server to forward the DNS query if embedded DNS server is unable to resolve a name resolution request from the containers. These --dns IP addresses are managed by the embedded DNS server and will not be updated in the container's /etc/resolv.conf file.

It pointing to `127.0.0.11` isn't something that needs to be "fixed".

**Comment by zim514** [comment] 2019-03-18 21:54
Hi,

I had the same issue as reported by the original poster, with the behaviour @diginc described of docker-compose not apparently respecting the dns config using version **4.2.2-1**

However, in addition to the logs pasted by @SeanChristopherConway, it looks like $ServerIP was being set to 0.0.0.0 on start up. Though pi.hole was resolving external addresses fine, pi.hole was resolving to 0.0.0.0. 

I had removed the ServerIP env var from my docker-compose.yml per the latest info on dockerhub, but I had to add it back for it to be set properly and everything went back to normal.

I still have the warning and the reference to 127.0.0.11, but pihole works perfectly now.

Additional notes:

- Not using pihole DHCP, using my gateway's built-in dnsmasq for dhcp and DNS.
- Pihole is pointing to my gateway's built in DNS to resolve internal IPs.
- Docker host is also pointing to my gateway's DNS.  This is to resolve an issue with other software on the host that needs DNS before docker & pihole come up. 

I've included the before and after pihhole logs and docker-compose. Please let me know if you need additional info.

**docker-compose**
NB: I snipped out other services, but they have no relation.

```yaml
version: '3.7'
   pihole:
      container_name: pihole
      image: pihole/pihole:latest
      environment:
        - TZ=America/Toronto
        - WEBPASSWORD=***********
        - DNS1=192.168.1.1
        - DNS2=no
        - ServerIP=192.168.1.10
      hostname: pihole
      dns:
        - 127.0.0.1
        - 192.168.1.1
      ports:
        - 443:443/tcp
        - 53:53/tcp
        - 53:53/udp
        - 80:80/tcp
      restart: unless-stopped
      volumes:
        - /storage/docker/dnsmasq:/etc/dnsmasq.d
        - /storage/docker/pihole:/etc/pihole
      labels:
        - "traefik.enable=false"
```
The ServerIP line is the only difference between the output of the below dumps.

**Pihole logs without ServerIP in docker-compose**
```
pihole        | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole        | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole        | [fix-attrs.d] applying ownership & permissions fixes...
pihole        | [fix-attrs.d] 01-resolver-resolv: applying...
pihole        | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole        | [fix-attrs.d] done.
pihole        | [cont-init.d] executing container initialization scripts...
pihole        | [cont-init.d] 20-start.sh: executing...
pihole        | stty: 'standard input': Inappropriate ioctl for device
pihole        |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole        | WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
pihole        | WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)
pihole        | search snapcase.ca
pihole        | nameserver 127.0.0.11
pihole        | options ndots:0
pihole        | stty: 'standard input': Inappropriate ioctl for device
pihole        |   [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u1
pihole        |   [i] Installing configs from /etc/.pihole...
pihole        |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [?] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
pihole        | chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
pihole        | ::: Pre existing WEBPASSWORD found
pihole        | Using custom DNS servers: 192.168.1.1 & no
pihole        | DNSMasq binding to default interface: eth0
pihole        | Added ENV to php:
pihole        |                         "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
pihole        |                         "ServerIP" => "0.0.0.0",
pihole        |                         "VIRTUAL_HOST" => "0.0.0.0",
pihole        | Using IPv4 and IPv6
pihole        | ::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
pihole        | # The below list amalgamates several lists we used previously.
pihole        | # See `https://github.com/StevenBlack/hosts` for details
pihole        | ##StevenBlack's list
pihole        | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
pihole        | ##MalwareDomains
pihole        | https://mirror1.malwaredomains.com/files/justdomains
pihole        | ##Cameleon
pihole        | http://sysctl.org/cameleon/hosts
pihole        | ##Zeustracker
pihole        | https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
pihole        | ##Disconnect.me Tracking
pihole        | https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
pihole        | ##Disconnect.me Ads
pihole        | https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
pihole        | ##Hosts-file.net
pihole        | https://hosts-file.net/ad_servers.txt
pihole        | ::: Testing pihole-FTL DNS: FTL started!
pihole        | ::: Testing lighttpd config: Syntax OK
pihole        | ::: All config checks passed, cleared for startup ...
pihole        |  ::: Docker start setup complete
pihole        |   [i] Pi-hole blocking is enabled
pihole        |   [i] Neutrino emissions detected...
  [?] Pulling blocklist source list into range
pihole        |   [i] Target: raw.githubusercontent.com (hosts)
  [?] Status: Retrieval successful
pihole        |   [i] Target: mirror1.malwaredomains.com (justdomains)
  [?] Status: Retrieval successful
pihole        |   [i] Target: sysctl.org (hosts)
  [?] Status: No changes detected
pihole        |   [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [?] Status: No changes detected
pihole        |   [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [?] Status: No changes detected
pihole        |   [i] Target: s3.amazonaws.com (simple_ad.txt)
  [?] Status: No changes detected
pihole        |   [i] Target: hosts-file.net (ad_servers.txt)
  [?] Status: No changes detected
  [?] Consolidating blocklists
  [?] Extracting domains from blocklists
pihole        |   [i] Number of domains being pulled in by gravity: 134594
  [?] Removing duplicate domains
pihole        |   [i] Number of unique domains trapped in the Event Horizon: 112287
  [i] Number of whitelisted domains: 4
pihole        |   [i] Number of blacklisted domains: 67
pihole        |   [i] Number of regex filters: 1
  [?] Parsing domains into hosts format
  [?] Cleaning up stray matter
pihole        |   [?] DNS service is running
pihole        |   [?] Pi-hole blocking is Enabled
pihole        | [cont-init.d] 20-start.sh: exited 0.
pihole        | [cont-init.d] done.
pihole        | [services.d] starting services
pihole        | Starting lighttpd
pihole        | Starting pihole-FTL (no-daemon) as root
pihole        | Starting crond
pihole        | [services.d] done.
```

**Pihole logs with ServerIP in docker-compose**
```
pihole        | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole        | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole        | [fix-attrs.d] applying ownership & permissions fixes...
pihole        | [fix-attrs.d] 01-resolver-resolv: applying...
pihole        | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole        | [fix-attrs.d] done.
pihole        | [cont-init.d] executing container initialization scripts...
pihole        | [cont-init.d] 20-start.sh: executing...
pihole        | stty: 'standard input': Inappropriate ioctl for device
pihole        |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole        | WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
pihole        | WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)
pihole        | search snapcase.ca
pihole        | nameserver 127.0.0.11
pihole        | options ndots:0
pihole        | stty: 'standard input': Inappropriate ioctl for device
pihole        |   [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u1
pihole        |   [i] Installing configs from /etc/.pihole...
pihole        |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [?] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
pihole        | chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
pihole        | ::: Pre existing WEBPASSWORD found
pihole        | Using custom DNS servers: 192.168.1.1 & no
pihole        | DNSMasq binding to default interface: eth0
pihole        | Added ENV to php:
pihole        |                         "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
pihole        |                         "ServerIP" => "192.168.1.10",
pihole        |                         "VIRTUAL_HOST" => "192.168.1.10",
pihole        | Using IPv4 and IPv6
pihole        | ::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
pihole        | # The below list amalgamates several lists we used previously.
pihole        | # See `https://github.com/StevenBlack/hosts` for details
pihole        | ##StevenBlack's list
pihole        | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
pihole        | ##MalwareDomains
pihole        | https://mirror1.malwaredomains.com/files/justdomains
pihole        | ##Cameleon
pihole        | http://sysctl.org/cameleon/hosts
pihole        | ##Zeustracker
pihole        | https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
pihole        | ##Disconnect.me Tracking
pihole        | https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
pihole        | ##Disconnect.me Ads
pihole        | https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
pihole        | ##Hosts-file.net
pihole        | https://hosts-file.net/ad_servers.txt
pihole        | ::: Testing pihole-FTL DNS: FTL started!
pihole        | ::: Testing lighttpd config: Syntax OK
pihole        | ::: All config checks passed, cleared for startup ...
pihole        |  ::: Docker start setup complete
pihole        |   [i] Pi-hole blocking is enabled
pihole        |   [i] Neutrino emissions detected...
  [?] Pulling blocklist source list into range
pihole        |   [i] Target: raw.githubusercontent.com (hosts)
  [?] Status: Retrieval successful
pihole        |   [i] Target: mirror1.malwaredomains.com (justdomains)
  [?] Status: No changes detected
pihole        |   [i] Target: sysctl.org (hosts)
  [?] Status: No changes detected
pihole        |   [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [?] Status: No changes detected
pihole        |   [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [?] Status: No changes detected
pihole        |   [i] Target: s3.amazonaws.com (simple_ad.txt)
  [?] Status: No changes detected
pihole        |   [i] Target: hosts-file.net (ad_servers.txt)
  [?] Status: No changes detected
  [?] Consolidating blocklists
  [?] Extracting domains from blocklists
pihole        |   [i] Number of domains being pulled in by gravity: 134594
  [?] Removing duplicate domains
pihole        |   [i] Number of unique domains trapped in the Event Horizon: 112287
  [i] Number of whitelisted domains: 4
pihole        |   [i] Number of blacklisted domains: 67
pihole        |   [i] Number of regex filters: 1
  [?] Parsing domains into hosts format
  [?] Cleaning up stray matter
pihole        |   [?] DNS service is running
pihole        |   [?] Pi-hole blocking is Enabled
pihole        | [cont-init.d] 20-start.sh: exited 0.
pihole        | [cont-init.d] done.
pihole        | [services.d] starting services
pihole        | Starting lighttpd
pihole        | Starting pihole-FTL (no-daemon) as root
pihole        | Starting crond
pihole        | [services.d] done.
```

**Comment by Natteverf** [comment] 2019-04-29 07:33
Hi All
 I have all of the above  same issues using v4.2.2.
`WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11),
nameserver 127.0.0.11,`
And having removed the ServerIP variable from my Docker Compose file, pi.hole does not resolve, I had to put it back in.

When will the resolv.conf issue be resolved (excuse the pun)? 
The ServerIP issue can be resolved by changing the documentation slightly?

Cheers!
Dave

**Comment by wrobelda** [comment] 2019-05-08 15:20
BTW. the 127.0.0.11 is required to be able to resolve other docker containers by hostname within the network scope. So if you're running other containers apart from pihole, you have to use the IP to reach them. Which is antipattern for pattern, as it by definition does not offer static IP for containers.

**Comment by halcyon22** [comment] 2019-06-02 14:59
If I'm understanding comments by @nightah and @wrobelda correctly, the pihole container's `/etc/resolv.conf` contains `127.0.0.11` by design. We then use e.g. `--dns=127.0.0.1 --dns=1.1.1.1` to cause name resolution to work the same as when pihole is run without a container.

If so, the problem is that these WARNINGs logged during startup are not valid:
```
WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)
```
I'm guessing that this is part of some DNS validation code in pihole itself which is unaware that in our case it's running inside a Docker container. To avoid confusion due to the false warnings during container startup, would it be reasonable to make one of the following changes?
1. Modify the DNS validation to be container-aware so that it recognizes `nameserver=127.0.0.11` as valid when within a Docker container.
2. Modify the warning to say something like "If run within a Docker container, `nameserver=127.0.0.11` is expected"?

If the maintainers decide that one of these options is desirable, I can add a feature request and take a shot at making the change.

**Comment by wrobelda** [comment] 2019-06-05 03:32
@halcyon22 Why do we even have to provide the default DNS in the first place? 

1. It's safe to assume that the host system has `/etc/resolv.conf` setup correctly with some non-pihole backup public DNS servers. It really is the only way to guarantee the DNS resolution to function properly after the host is booted and before docker boots its containers (including pihole), so I can't imagine any scenario where this isn't done. 
2. Docker has its own DNS resolver (`127.0.0.11`) that reads the `/etc/resolv.conf` entries. So we don't have to provide a backup server to the container itself, docker already handles that. 
3. I don't see the need for providing `--dns=127.0.0.1`, either. The `README` says that it "Sets your container's resolve settings to localhost so it can resolve DHCP hostnames from Pi-hole's DNSMasq". Why is this needed at all? Is there any reason to resolve the DHCP hostnames from within the container itself? 

With no overrides provided and the default `127.0.0.53` as the only resolver, everything works for me as it should – except for the docker's container hostname resolution. For that pihole would have to query `127.0.0.53`, too.

**Comment by diginc** [comment] 2019-06-05 22:32
Please see https://github.com/pi-hole/docker-pi-hole/issues/431 for a discussion on the background of using 127.0.0. DNS.  We discuss the alternative to using this method a little in there too.  I'll be working on that task more this month.

**Comment by abhijeetgaiha** [comment] 2020-01-27 14:59
I see this issue on windows with the latest docker.

**Comment by AuspeXeu** [comment] 2020-03-11 23:16
Same issue still persists for me as well on a raspberry pi.

**Comment by edgd1er** [comment] 2020-03-19 00:28
Well, I have the same problem (healthcheck: unhealthy, no server found). DNS resolution were performed, stats were available, ads were piholed, but I use traefik, to access pihole's web stats, which is not possible when the container is not healthy. traefik remove it from the list of available services.

my temporary solution was to set docker-compose language version to 3.4 and to rewrite the healhcheck. my understanding is that the healthcheck is now using docker internal dns (the one defined with the -dns x.x.x.x). I'm not sure it was designed to operate so, by pihole's maintainer.
in the docker-compose: .....
```
   healthcheck:
      test: ["CMD", "dig", "+norecurse","+retry=0","@127.0.0.11","pi.hole"," || exit 1"]
      interval: 1m05s
      timeout: 10s
      retries: 0
      start_period: 40s


``

**Comment by JamborJan** [comment] 2020-04-09 16:01
From my point of view it's clear:

The "release-v4.3.4" version has this HEALTHCHECK which is working:
```
HEALTHCHECK &{["CMD-SHELL" "dig @127.0.0.1 
```

and the "v4.4" version has this HEALTHCHECK which is not working:

```
HEALTHCHECK &{["CMD-SHELL" "dig +norecurse
```

I tested most of the proposed workarounds, nothing helped. Only reverting to v4.3.4.

Funny: the latest tag  as well as the betav5 tag have the working version of the HEALTHCHECK.

Maybe @mr-bolle or someone else at pi-hole could rebuild the 4.4 image or create a 4.4.1 to fix that. I don't like running "latest" images and auto updates. Just because of wht happened here :-)

Off topic: why are the tags completely different all the time?
- release-v4.3.4
- v4.3.4
- 4.3.2-1
?

**Comment by lightswitch05** [comment] 2020-04-09 17:00
@JamborJan the healthcheck change can be found here: https://github.com/pi-hole/docker-pi-hole/pull/579. I made the change because the previous health check would report healthy even if 2/3rds of the requests were failing. Not to say I couldn't get something with the healthcheck changes, but I would also be very skeptical of the previous version saying its healthy.

**Comment by JamborJan** [comment] 2020-04-09 17:23
Thanks for the explanation. This means something in my setup is wrong? Everything seems to work, only the health check is failing as described above.

**Comment by lightswitch05** [comment] 2020-04-09 17:37
I can't speak to you setup. What I can do is explain my changes. The change I made was adding `+norecurse +retry=0` to the healthcheck. That means it (`dig`) will only try 1 time (`+retry=0`) to resolve the query, and that it will not use recursive DNS to resolve it. This is done because ONLY the pihole should have the answer for `pi.hole`. The pihole should not need to do a recursive query to resolve it. If your pihole does not know the answer to a `pi.hole` query, then it is considered unhealthy.

**Comment by mr-bolle** [comment] 2020-04-09 17:37
Hi @JamborJan, 

i create a new pihole container - i use the docker-compose [example](https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose.yml) and i don't see any issues with the healthcheck. (this topic isn't connected with the current issue)

```
$ docker-compose ps
   Name      Command       State                                          Ports                                   
------------------------------------------------------------------------------------------------------------------
pihole-dev   /s6-init   Up (healthy)   443/tcp, 0.0.0.0:53->53/tcp, 0.0.0.0:53->53/udp, 67/udp, 0.0.0.0:88->80/tc
```

**Comment by JamborJan** [comment] 2020-04-09 18:07
Thank you both I will investigate further. Sorry for bombing this issue with another topic, I was reading through it and as the last post before mine was talking about the exact issue I have I thought it would be the same. Sorry for that.

**Comment by kanonengedonner** [comment] 2020-05-20 04:09
I am not sure I understand the solution to docker not respecting the --dns 127.0.0.1 argument in my case. I am on docker on synology and my docker-compose is the following:

```
version: '2'
services:
 pihole:
   container_name: pihole
   image: pihole/pihole:latest
   networks:
     pihole_network:
       ipv4_address: 192.168.3.200
   volumes:
     - "/volume1/docker/AppData/Pi-hole/etc-pihole/:/etc/pihole/"
     - "/volume1/docker/AppData/Pi-hole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
   dns:
     - 127.0.0.1
     - 8.8.8.8
   ports:
     - 443/tcp
     - 53/tcp
     - 53/udp
     - 67/udp
     - 80/tcp
   environment:
     TZ: America/New_York
     ServerIP: 192.168.3.3
   restart: unless-stopped
networks:
 pihole_network:
   driver: macvlan
   driver_opts:
     parent: ovs_eth0
   ipam:
     config:
       - subnet: 192.168.3.0/24
         gateway: 192.168.3.1
         ip_range: 192.168.3.200/32
```
The log shows:

    
```
(...)
WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)
nameserver 127.0.0.11
options ndots:0
Assigning random password: HzrRd9b3
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u7
chown: cannot access '': No such file or directory
  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf...
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chmod: cannot access '': No such file or directory
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
Docker DNS variables not used
Existing DNS servers used (8.8.8.8 & 8.8.4.4)
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"VIRTUAL_HOST" => "0.0.0.0",
(...)
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
 ::: Docker start setup complete
  [✗] DNS resolution is currently unavailable
```
This suggested solution doesn't seem to be valid in my case:

```
$ echo -e "nameserver 127.0.0.1\nnameserver 1.1.1.1" > overwrite_resolv.conf
$ docker run -it -v $(pwd)/overwrite_resolv.conf:/etc/resolv.conf debian cat /etc/resolv.conf
nameserver 127.0.0.1
nameserver 1.1.1.1
```

**Comment by kanonengedonner** [comment] 2020-05-20 21:50
Ok...this seems to have been fixed by deleting 

```dns:```
```- 127.0.0.1```
```- 8.8.8.8```

from the yml code....any one care to explain why?

**Comment by el-vishal** [comment] 2020-06-01 00:14
Seems like Pi-hole works irrespective of `Misconfigured DNS 127.0.0.11 warning`

I was facing the exact same warning, along with service errors
`pihole_1         | chown: cannot access '': No such file or directory
pihole_1         | chmod: cannot access '': No such file or directory
pihole_1         | chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
`

Not mounting var logs strangely solved it

**Comment by IrritatedGoat** [comment] 2020-06-23 14:29
I'm having the same issue. 

My docker-compose is 

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: $password
      ServerIP: 192.168.0.112
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped  
```
Admin page doesn't resolve. The health check shows it is healthy but the logs show

```
pihole    | WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
pihole    | WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)
pihole    |
pihole    | nameserver 127.0.0.11
pihole    | options ndots:0
pihole    |   [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u7
pihole    |
pihole    |   [i] Installing configs from /etc/.pihole...
pihole    |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
pihole    | chown: cannot access '': No such file or directory
pihole    | chmod: cannot access '': No such file or directory
pihole    | chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
```

**Comment by Tyrian81** [comment] 2020-07-25 09:54
Having the same issue as above , cant get it up and running ?

`version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: '******'
    # Volumes store your data between container upgrades
    volumes:
      - '/storage/docker/etc-pihole/:/etc/pihole/'
      - '/storage/docker/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
`

`WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)
search home
nameserver 127.0.0.11
options ndots:0
Failed to set capabilities on file `/usr/bin/pihole-FTL' (Operation not supported)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
  [i] Update local cache of available packages...
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u8
  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf...
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
mv: cannot move '/etc/lighttpd/lighttpd.conf' to a subdirectory of itself, '/etc/lighttpd/lighttpd.conf.orig'
[cont-init.d] 20-start.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
`

**Comment by dantebarba** [comment] 2020-08-26 23:15
Same issue here. Fortunately pihole starts but I would like to set the DNS servers on startup.

**Comment by rednag** [comment] 2021-02-06 14:01
> I've got similar issue running Pi-hole docker. Here is my docker-compose:
> 
> ```
> services:
>  Pi-hole:
>     container_name:   "Pi-hole"
>     image:            "pihole/pihole:latest"
>     restart:          always
>     networks:
>       local_net:
>         ipv4_address: 192.168.1.120
>     cap_add:
>       - NET_ADMIN
>     dns:
>       - 127.0.0.1
>       - 1.1.1.1
>     volumes:
>       - /Dockers/Pi-hole/etc:/etc/pihole/
>       - /Dockers/Pi-hole/dnsmasq.d:/etc/dnsmasq.d/
>     environment:
>       - ServerIP=192.168.1.120
>       #- ServerIPv6=${IPv6}
>       - DNSMASQ_LISTENING=all
>       - TZ=Europe/London
>       - DNS1=127.0.0.1
>       - DNS2=1.1.1.1
> 
> networks:
>   local_net:
>     name: local_net
>     driver: macvlan
>     #attachable: true
>     driver_opts:
>       parent: eth0
>     ipam:
>       #driver: macvlan
>       config:
>         - subnet: 192.168.1.0/24
> ```
> 
> Here is debug log:
> 
> ```
> WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server,
> [cont-init.d] 20-start.sh: executing... ,
> stty: 'standard input': Inappropriate ioctl for device,
>  ::: Starting docker specific setup for docker pihole/pihole,
> WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11),
> nameserver 127.0.0.11,
> options ndots:0,
>   [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u1,
>   [i] Installing configs from /etc/.pihole...,
>   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
> ```

Fixed for me DNS issue at start up of my pi hole docker via docker-compose

`version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    hostname: pihole
    restart: always
    environment:
      TZ: Europe/Israel
      WEBPASSWORD: "XXX"
      DNS1: 127.0.0.1 # Added this DNS
      DNS2: 1.1.1.1 # Added this DNS
    dns:
      - 127.0.0.1 # Added this DNS
      - 1.1.1.1 # Added this DNS
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    cap_add:
      - NET_ADMIN`

Before I had the issue that always when I've started my docker-compose the pihole docker was not accessible via Web UI. After adding the DNS servers the container started like a charm.

**Comment by MichaIng** [comment] 2021-07-22 10:03
The warnings have been removed with #618, so the `docker run --dns`, respectively Docker Compose `dns:` entries should be respected. It is btw not advised (anymore) to use Pi-hole itself by the Pi-hole's server/container for name resolution, so it cannot lockout itself. The native Pi-hole installer does not apply this anymore and Pi-hole itself does not depend on it.

**Closed** 2022-01-16 19:02 UTC
Labels: Submitter Attention Required
