### ISSUE TITLE
Serious issue with setupVars.conf file

### ISSUE THREAD

**Issue by TheGITofTeo997** [pi-hole/docker-pi-hole#719] opened 2020-12-03 16:27 UTC
### Versions

This has been happening since PiHole version 5.x.x, dockerized.

### Platform

- OS and version:  Raspbian Buster

- Platform:  Raspberry Pi 3.

### Expected behavior

When you stop/restart/recreate a container, settings should be correctly kept and read from setupVars.conf file, since the container has the mounted directory etc-pihole. So a simple upgrade should not affect your settings.

### Actual behavior / bug

When you stop/restart/recreate a container, for some reason the *mounted* setupVars.conf file gets overwritten with default settings. For example if i had custom upstream DNSs, i get the Google ones, and every setting is lost (not talking about adLists, etc..). As a consequence the whole web gui interface stops working and responding, if you try to contact it from your browser you get an error. I noticed i get default values because i've read the new overwritten setupVars and because i did a DNS leak test, which resulted in Google and not in my custom servers. 

This keeps happening in every version and on different setup/machines, also tried my friend's one.
The only workaround i got for this is to backup the old setupVars.conf, and after the new container is created (with the new updated image), i replace it in the mounted etc-pihole folder. After doing this simple step, the GUI gets responsive and all is working without even restarting the container. For some reason even after a Pi restart, everything keeps working and all is fixed. Of course this is not the expected bevahior.

### Steps to reproduce

Just recreate or restart a container.

## Debug Token

- URL:  -

**Comment by PromoFaux** [comment] 2020-12-03 16:33
Dupe of #668

**Comment by TheGITofTeo997** [comment] 2020-12-03 16:37
@PromoFaux yeah, i'm sorry i didn't notice it.

**Comment by PromoFaux** [comment] 2020-12-03 16:37
No problem. 

It's something we're aware of. Once I have my head around the docker processes I'll take a closer look at it. In the mean time, set environment variables for anything you want persisted - that seems to work

**Comment by TheGITofTeo997** [comment] 2020-12-03 16:39
@PromoFaux Thanks, i am using a .sh start script, i think i will manage to get those there.

**Comment by PromoFaux** [comment] 2020-12-03 17:23
Closed in place of the pinned #720

**Closed by PromoFaux** 2020-12-03 17:23 UTC
Labels: duplicate
