### ISSUE TITLE
Error, something went wrong! While executing INSERT OT IGNORE: attempt to write a readonly database Added 0 out of 1 domains

### ISSUE THREAD

**Issue by unurgunite** [pi-hole/docker-pi-hole#915] opened 2021-09-06 13:41 UTC
**Versions**
 - Pi-hole version is v5.3.1 (Latest: v5.3.1)
 - AdminLTE version is v5.5.1 (Latest: v5.5.1)
 - FTL version is v5.8.1 (Latest: v5.8.1)

**Platform**
 - Docker setup from https://github.com/IAmStoxe/wirehole

**Expected behaviour**
 I went to `http://my_ip/admin/groups-domains.php?type=black` and tried to add a domain to blacklist. Since then this domain is not accessible from my network

**Actual behaviour**
I went to `http://my_ip/admin/groups-domains.php?type=black` and tried to add a domain to the blacklist, but instead get an error inside the red block: 
```
Error, something went wrong!
While executing INSERT OT IGNORE: attempt to write a readonly database
Added 0 out of 1 domains
```

P.S: I have the same issue with whitelist. On top of that, `pihole -w example.com` and `pihole -b example.com` works without any errors

**Comment by asyba** [comment] 2021-09-09 00:40
same issue with new fresh install on Rpi4

**Comment by lightswitch05** [comment] 2021-12-14 21:18
I believe this is a duplicate of #860

**Closed** 2022-01-11 10:07 UTC

**Comment by freebrowser1** [comment] 2023-07-29 13:15
Run as root:
```
usermod -aG www-data pihole
usermod -aG pihole www-data
chown pihole:www-data /etc/pihole/*
chown pihole:www-data /etc/pihole/.
```
 solved the problem for me.
It is allowing the pihole and Apache user each into each others groups.
And setting ownership of the `/etc/pihole` folder and files to pihole user and groupship Apache user.
