### ISSUE TITLE
opening errorlog '/var/log/lighttpd/error.log' failed: Permission denied Stopping lighttpd

### ISSUE THREAD

**Issue by krauthammer18** [pi-hole/docker-pi-hole#433] opened 2019-03-02 16:15 UTC
I can't get the lastest version of pihole to work on a brand new container in Openmediavault 4.1.19.  It repeats the same error over and over. I am using the following environment variables:

WEBPASSWORD: temppass
TZ: America/Los_Angeles
DNS1: 127.0.0.1
DNS2: 1.1.1.1

volumes:
/etc/pihole
/etc/dnsmasq.d

And these are extra arguments
-p 53:53 -p 67:67/udp -p 80:80/tcp -p 443:443/tcp --cap-add=NET_ADMIN

Here is the entire log output during startup:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing...
stty: 'standard input': Inappropriate ioctl for device
 ::: Starting docker specific checks & setup for docker pihole/pihole
WARNING Misconfigured DNS in /etc/resolv.conf: Two DNS servers are recommended, 127.0.0.1 and any backup server
WARNING Misconfigured DNS in /etc/resolv.conf: Primary DNS should be 127.0.0.1 (found 127.0.0.11)

search home.local
nameserver 127.0.0.11
options ndots:0
stty: 'standard input': Inappropriate ioctl for device
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u1

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf...[K  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
+ pihole -a -p 'temppass' 'temppass'
Setting password: temppass
  [✓] New password set
Using custom DNS servers: 127.0.0.1 & 1.1.1.1
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "10.10.1.17",
			"VIRTUAL_HOST" => "10.10.1.17",
Using IPv4 and IPv6
::: setup_blocklists now setting default blocklists up:
::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
::: Blocklists (/etc/pihole/adlists.list) now set to:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
 ::: Docker start setup complete
  [i] Pi-hole blocking is enabled
  [i] Neutrino emissions detected...
[K  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: sysctl.org (hosts)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Target: hosts-file.net (ad_servers.txt)
  [i] Status: Pending...[K  [✓] Status: Retrieval successful

  [i] Consolidating blocklists...[K  [✓] Consolidating blocklists
  [i] Extracting domains from blocklists...[K  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 135325
  [i] Removing duplicate domains...[K  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 112862
  [i] Nothing to whitelist!
  [i] Number of regex filters: 0
  [i] Parsing domains into hosts format...[K  [✓] Parsing domains into hosts format
  [i] Cleaning up stray matter...[K  [✓] Cleaning up stray matter

  [✓] DNS service is running
  [i] Pi-hole blocking will be enabled
  [i] Enabling blocking
[K  [✓] Pi-hole Enabled
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting pihole-FTL (no-daemon) as root
Starting lighttpd
Starting crond
[services.d] done.
2019-03-02 16:03:45: (log.c.171) opening errorlog '/var/log/lighttpd/error.log' failed: Permission denied
Stopping lighttpd
lighttpd: no process found
Starting lighttpd
2019-03-02 16:03:46: (log.c.171) opening errorlog '/var/log/lighttpd/error.log' failed: Permission denied
Stopping lighttpd
lighttpd: no process found
Starting lighttpd
2019-03-02 16:03:47: (log.c.171) opening errorlog '/var/log/lighttpd/error.log' failed: Permission denied
Stopping lighttpd
lighttpd: no process found
Starting lighttpd
2019-03-02 16:03:48: (log.c.171) opening errorlog '/var/log/lighttpd/error.log' failed: Permission denied
Stopping lighttpd
lighttpd: no process found
Starting lighttpd
2019-03-02 16:03:49: (log.c.171) opening errorlog '/var/log/lighttpd/error.log' failed: Permission denied
Stopping lighttpd
lighttpd: no process found

**Comment by mazafra1** [comment] 2020-01-21 11:14
Me too. Should we run the container with PUID=0 and PGID=0?

**Comment by kekec777** [comment] 2020-02-16 23:42
Any news / updates on this issue?

**Comment by clmbmb** [comment] 2020-06-24 08:49
I have the same issue all of a sudden. Two days ago I was able to login to the admin interface, but now I can't. The DNS service runs just fine, but the admin interface is dead.

Any dev have any time to look into this?

**Comment by clmbmb** [comment] 2020-06-24 09:05
Switched to the dev tag and it works. Hopefully this gets looked into.

**Comment by dschaper** [comment] 2020-06-24 17:27
@lightswitch05 Is the weekly rebuild going on?

**Comment by lightswitch05** [comment] 2020-06-24 17:33
@dschaper there is a nightly build of `beta-v5.0` in this project: https://github.com/pi-hole/docker-pi-hole/blob/master/.circleci/config.yml#L72

The weekly build is in the upstream `docker-base-images` images, which appear to be working correctly: https://github.com/pi-hole/docker-base-images/actions

the upstream image builds do not directly affect this project.

**Comment by lightswitch05** [comment] 2020-06-24 17:35
is this just a duplicate of https://github.com/pi-hole/docker-pi-hole/issues/268?

**Comment by lightswitch05** [comment] 2020-06-24 17:42
also #252

**Comment by xerosanyam** [comment] 2020-07-13 10:02
getting this error on lastest

**Comment by idotj** [comment] 2021-07-15 18:14
In my case this fix the problem:

Go to `/var/log` and change the permissions in the folder _lighttpd_ by typing:
`sudo chown -R www-data:www-data lighttpd/`

Then you can restart the service:
` service lighttpd restart`

Check if the web interface works:
`sudo systemctl status lighttpd -l`

**Closed** 2022-01-16 19:02 UTC
Labels: Submitter Attention Required
