### ISSUE TITLE
lighttpd says "unknown config-key" in error-pihole.log

### ISSUE THREAD

**Issue by thomasmerz** [pi-hole/docker-pi-hole#1273] opened 2023-01-16 09:34 UTC
This is a: **Bug**  

## Details
I found (by accident) these messages inside my docker container in /var/log/lighttpd/error-pihole.log:
```
2023-01-16 10:20:01: configfile.c.1142) WARNING: unknown config-key: accesslog.filename (ignored)
2023-01-16 10:20:01: configfile.c.1142) WARNING: unknown config-key: accesslog.format (ignored)
```

Because I didn't find these "config-key(s)" in my lighttpd.conf, I wanted to inform you about this if you're not already aware of it.

## Environment:
Docker Tag [2023.1.1](https://github.com/pi-hole/docker-pi-hole/releases/2023.1.1) Pi-hole [v5.15](https://github.com/pi-hole/pi-hole/releases/v5.15) FTL [v5.20.1](https://github.com/pi-hole/FTL/releases/v5.20.1) Web Interface [v5.18.1](https://github.com/pi-hole/AdminLTE/releases/v5.18.1)

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

**Comment by edgd1er** [comment] 2023-01-16 09:36
Yes noticed that also on latest version. Accesslog module is not loaded anymore,  could be fixed running:
```
lighttpd-enable-mod accesslog
```
this should be added during the install process, not sure though the root cause for this change.

**Comment by PromoFaux** [comment] 2023-01-16 10:02
It's all in the release notes 😉 https://discourse.pi-hole.net/t/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/60495

Although in this case this is a bug/oversight that we can sort out

Some changes were made in core to prevent clobbering of the default `lighttpd.conf` on new installs, and as such the pi-hole related configuration is placed in [`/etc/lighttpd/conf-enabled/15-pihole-admin.conf`](https://github.com/pi-hole/pi-hole/blob/master/advanced/pihole-admin.conf)


As a docker install is effectively a fresh install of Pi-hole, it does not have the old custom Pi-hole `lighttpd.conf` which contains the following lines:

https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian#L18-L26


>( and / is not redirected to /admin, but this is another subject. not found the cause yet )

How are you accessing the web interface? `http://pi.hole` will automatically redirect to `/admin`, but `http://ipaddress` will not. (Again, see the release notes)

However:  pull `latest` again if you have not done so since the initial release, as it now includes  https://github.com/pi-hole/docker-pi-hole/pull/1271 which will do the redirect to `/admin` on either one of `http://pi.hole` `http://$VIRTUAL_HOST` or `http://FTLCONF_LOCAL_IPV4`

**Comment by pluim003** [comment] 2023-01-16 13:14
Is it just me or is true that it doesn't work with https://$VIRTUAL_HOST ? Because instead of a page not found when accessing https://$VIRTUAL_HOST I get the default lighttpd-screen:

![afbeelding](https://user-images.githubusercontent.com/67138922/212686572-675af778-5a38-40d4-ae52-0af1c111b39f.png)

**Comment by PromoFaux** [comment] 2023-01-16 13:16
The key here may be `http` vs `https`..,

**Comment by PromoFaux** [comment] 2023-01-16 13:20
@pluim003 if you append `/admin` to the URL, does the web interface work correctly?

**Comment by PromoFaux** [comment] 2023-01-16 13:27
Here it is working for me:

![image](https://user-images.githubusercontent.com/1998970/212688110-89c26d6e-c0d4-43a9-bb84-c49206015197.png)
![it redirects](https://user-images.githubusercontent.com/1998970/212689059-43d0fd63-52a0-4da4-8d72-e53fdaab1207.gif)

**Comment by pluim003** [comment] 2023-01-16 14:12
> @pluim003 if you append `/admin` to the URL, does the web interface work correctly?

Then it works. I need to test it at home when connected to my local network if FTLCONF_LOCAL_IP4-variant is being used when trying to logon to http:/10.0.0.10 . 
My https://pihole.something is behind the nginx proxy manager. 
For my 2nd pihole which is in another network it worked 'already since ages'. Entering http://192.168.178.35:8100 gave me immediately the /admin/index.php

**Comment by PromoFaux** [comment] 2023-01-16 17:01
@pluim003 I've just checked with https (I put my Pi-hole behind my Traefik reverse proxy - same principle as nginx) and can confirm that the redirect on `https://VIRTUAL_HOST` works fine

![image](https://user-images.githubusercontent.com/1998970/212731548-3ebeb56a-a4d3-4403-82f8-8c22627ae4c5.png)

![Stillworks](https://user-images.githubusercontent.com/1998970/212731806-ee7009ba-f0a3-43a6-bb48-2fcf4e66c420.gif)

Ordinarily I wouldn't have my admin page exposed to the internet - but I'll leave it up for a bit so that you can see it working: https://pihole1.promofaux.dev

**Comment by PromoFaux** [comment] 2023-01-16 17:08
I'll never pass up an opportunity to go out of my way to prove someone wrong 😉

I jest, really I just wanted to make sure that there wasn't a bug -and now if someone else says they have the same issue, I have somewhere to point them :)

**Comment by PromoFaux** [comment] 2023-01-16 22:31
@thomasmerz @edgd1er - the originally reported issue in this thread will be fixed in the next release:

https://github.com/pi-hole/pi-hole/pull/5121

**Comment by pluim003** [comment] 2023-01-17 10:08
> Great, it's a nginx-issues I guess. Probably some misconfiguration from my side. Will dig into this later. Thanx for clarification and confirming that it should work.

A miracle happened: all of a sudden today when I enter https://$VIRTUAL_HOST /admin is being added automagically. Probably this nightly build (as I use on this one a nightly build) wasn't that up-to-date yesterday. And I use the nightly build to create an image which includes the latest version of Unbound (well from Debian testing).

**Comment by PromoFaux** [comment] 2023-01-22 22:17
@thomasmerz should now be sorted in 2023.01.8

**Closed by PromoFaux** 2023-01-22 22:17 UTC
Labels: Fixed in next release, Waiting on Pi-hole Core release

**Comment by thomasmerz** [comment] 2023-01-23 16:43
@PromoFaux , this warning has vanished with 2023.01.8 👍🏼 (you and the Pi-hole team are pretty productive these days 😉 )

**Comment by thomasmerz** [comment] 2023-01-23 17:35
But the last days you have been hyper-productive - so many new releases 😄
