### ISSUE TITLE
Crashing on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by LoSunny** [pi-hole/docker-pi-hole#935] opened 2021-10-28 02:36 UTC
After running the container for some hours, I won't be able to SSH or view the screen of the pi. Everything is dead and I need to unplug the power and power the pi back on in order to get access to the pi.

This is a: Bug

## Details

Here are the logs for pi-hole and syslog: https://gofile.io/d/NuNe0d
The crash happens around 22.00 to 24.00

## Related Issues
- [*] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

But sadly none

## How to reproduce the issue 

1. Environment data
  * Operating System: Rasbian 
  * Hardware: 3B+
  * Kernel Architecture: ArmV7 32bit
  * Docker Install Info and version: 
    - Software source: official docker-ce
    - Supplimentary Software: NIL
  * Hardware architecture: ARMv7

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "30000:80/tcp"
      - "30001:443/tcp"
    environment:
      TZ: 'Asia/Hong_Kong'
      WEBPASSWORD: '2January2003'
      VIRTUAL_HOST: 'pihole.sunnylo.tk'
      DNS1: '172.18.0.3#5054'
    volumes:
      - '/home/pi/Documents/pi-hole/pihole/pihole/:/etc/pihole/'
      - '/home/pi/Documents/pi-hole/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 172.18.0.2

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:alpine-3.12
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 172.18.0.3

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
      - SERVERURL=wireguard.sunnylo.tk
      - SERVERPORT=51820
      - PEERS=SunnyiPhone,SunnyiPad,SunnyMBA,SamiPhone,SamWin
      - PEERDNS=172.18.0.2
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /home/pi/Documents/pi-hole/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 172.18.0.4

networks:
  pihole:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
```

## These common fixes didn't work for my issue

- [*] I have tried removing/destroying my container, and re-creating a new container
- [*] I have tried fresh volume data by backing up and moving/removing the old volume data
- [*] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [*] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by AndrejSayadov** [comment] 2022-01-02 16:13
Hi! I have the same problem
Log:
`pihole           | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole           | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole           | [fix-attrs.d] applying ownership & permissions fixes...
pihole           | [fix-attrs.d] 01-resolver-resolv: applying...
pihole           | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole           | [fix-attrs.d] done.
pihole           | [cont-init.d] executing container initialization scripts...
pihole           | [cont-init.d] 20-start.sh: executing...
pihole           |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole           |
pihole           |   [i] Installing configs from /etc/.pihole...
pihole           |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
pihole           | Existing DNS servers detected in setupVars.conf. Leaving them alone
pihole           |   [✓] New password set
pihole           | DNSMasq binding to default interface: eth0
pihole           | Added ENV to php:
pihole           |                      "PIHOLE_DOCKER_TAG" => "2021.12.1",
pihole           |                      "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
pihole           |                      "ServerIP" => "0.0.0.0",
pihole           |                      "CORS_HOSTS" => "",
pihole           |                      "VIRTUAL_HOST" => "0.0.0.0",
pihole           | Using IPv4 and IPv6
pihole           | ::: setup_blocklists now setting default blocklists up:
pihole           | ::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
pihole           | ::: Blocklists (/etc/pihole/adlists.list) now set to:
pihole           | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
pihole           | ::: Testing pihole-FTL DNS: FTL started!
pihole           | ::: Testing lighttpd config: Syntax OK
pihole           | ::: All config checks passed, cleared for startup ...
pihole           | ::: Enabling Query Logging
pihole           |   [i] Enabling logging...
  [✓] Logging has been enabled!
pihole           |  ::: Docker start setup complete
pihole           |   Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
pihole           |   Pi-hole version is v5.7 (Latest: v5.7)
pihole           |   AdminLTE version is v5.9 (Latest: v5.9)
pihole           |   FTL version is v5.12.1 (Latest: v5.12.1)
pihole           |   Container tag is: 2021.12.1
pihole           | [cont-init.d] 20-start.sh: exited 0.
pihole           | [cont-init.d] done.
pihole           | [services.d] starting services
pihole           | Starting lighttpd
pihole           | Starting pihole-FTL (no-daemon) as root
pihole           | Starting crond
pihole           | [services.d] done.
pihole           | /usr/bin/php-cgi: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory
pihole           | /usr/bin/php-cgi: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory
pihole           | /usr/bin/php-cgi: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory
pihole           | /usr/bin/php-cgi: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory`

**Comment by AndrejSayadov** [comment] 2022-01-03 06:34
the problem is in the latest tag. Use the specific tag from [https://github.com/pi-hole/docker-pi-hole/releases](here)  to run the counter.

**Comment by edgd1er** [comment] 2022-01-03 09:01
I had similar problem with a rpi, it was the sd card that was being corrupted, finally, the RPi would not start as boot file were corrupted also. Did you try with a new sd card ?
Also I noticed as usb and network are on the same bus, having a problem with a hard disk will impair the network access.
I tried to have a look to your logs, but that are indicated as not found.

**Comment by AndrejSayadov** [comment] 2022-01-03 10:12
I run image pihole/pihole:2021.12.1, it's ok!

**Comment by AndrejSayadov** [comment] 2022-01-03 10:13
Problem run with pihole/pihole:latest

**Comment by PromoFaux** [comment] 2022-01-03 20:07
`latest` and `2021.12.1` are the same image...


![image](https://user-images.githubusercontent.com/1998970/147975080-8a7c8f76-bcb0-43e7-823e-cb7d10c4d4d1.png)


Also closing as this issue is from October. @LoSunny - if this is still an issue for you, please reopen

**Closed by PromoFaux** 2022-01-03 20:07 UTC
