### ISSUE TITLE
Setting `DNS1` to an IP with a port results in the port being removed during runtime

### ISSUE THREAD

**Issue by fletchto99** [pi-hole/docker-pi-hole#1241] opened 2022-11-20 23:44 UTC
This is a: Run issue

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

1. Environment data
  * Operating System: Unraid
  * Hardware: PC
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: 
    - Software source: Official Source
    - Supplimentary Software: Docker
  * Hardware architecture: x86 

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here:

This configuration:
![pd2IImxbXs](https://user-images.githubusercontent.com/718681/202932899-ff643ae8-ede9-463d-8f1f-a49f475f7e7a.png)

results in this setting:
![ur9h5DQjMT](https://user-images.githubusercontent.com/718681/202932908-6d3f2660-6ce0-42b1-a598-0dbf24d1b9ec.png)

3. any additional info to help reproduce

The expected setting would be:
![pd2IImxbXs](https://user-images.githubusercontent.com/718681/202932919-b181b68b-3a0a-4a97-8fcd-c14ae608889d.png)

**NOTE:** This used to work but a recent version of pihole's docker container seems to have broken things. I haven't had a chance to debug which version broke it yet. I had unraid set to auto-update the pihole docker but only noticed things broke within the past month or so.

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container
- [x] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] ~I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)~ N/A since this relies on cusom configs
- [ ] TODO: I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by fletchto99** [comment] 2022-11-20 23:47
I believe the issue occurs in the function which transforms the `DNS1` var to `PIHOLE_DNS_` var: https://github.com/pi-hole/docker-pi-hole/blob/41aa699aab8346e7a9a32574d9ec168fc54490cc/src/s6/debian-root/usr/local/bin/bash_functions.sh#L263-L330

As you can see they do not match as I would probably expect them to:
![iZHmh2NyZ6](https://user-images.githubusercontent.com/718681/202933139-cd79ea15-63ce-4442-b3a4-bb07377fbdf0.png)

**Comment by PromoFaux** [comment] 2022-11-21 07:09
Can you try setting the values directly in the `PIHOLE_DNS_` variable? `DNS1` & `DNS2` have been deprecated for a while now.

**Comment by fletchto99** [comment] 2022-11-21 07:32
> Can you try setting the values directly in the PIHOLE_DNS_ variable? DNS1 & DNS2 have been deprecated for a while now.

Oh 🤦 - I'm using unraid and I think the template updated a while ago to use `PIHOLE_DNS_`. It was `10.10.10.1` while `DNS1` was `10.10.10.1#5053`. Anyhow long story short, dropping DNS1 and updating the value of `PIHOLE_DNS_` to be `10.10.10.1#5053` fixed the issue. Sorry for the noise.

**Comment by PromoFaux** [comment] 2022-11-21 08:58
No worries, it may be that the code to convert them is broken.. I'll reopen the issue for tracking purposes, as it probably _should_ work if we're going to try to be helpful and convert deprecated variables to supported ones!

**Comment by fletchto99** [comment] 2023-01-11 18:51
@PromoFaux Was going through some open issues I had and circled back to this one. I took a look a the code and it seem to be solid. I was also able to confirm that my template at the time was incorrect using the wrong value for `PIHOLE_DNS_` so the issue was totally on my end. I'll leave it up to you if you wish to still further investigate but I can definitely confirm the problem on my end was due to a bad set of env vars being passed to the container.

**Comment by PromoFaux** [comment] 2023-01-18 23:22
Thanks for the reminder - I meant to look at it a while back but forgot, however I just tried it myself and I cannot reproduce... so I don't really understand what happened! I will close this as the issue no longer appears to exist, I don't recall fixing it, but who knows.... sleep deprivation can do strange things

**Closed by PromoFaux** 2023-01-18 23:22 UTC
Labels: bug
